# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(help_text='The current count.')),
                ('last_update', models.DateTimeField(help_text='Last time the counter was updated.')),
            ],
        ),
    ]
