# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, help_text='The current count.')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last time the counter was updated.')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'S3_FILE_UPLOADED'), (2, 'QUEUED'), (3, 'S3_FILE_DOWNLOADED'), (4, 'FORECAST_LOADED')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_failed', models.BooleanField(default=False)),
                ('failure_message', models.CharField(max_length=2000)),
                ('filename', models.CharField(max_length=200)),
            ],
        ),
    ]
